relaxed.remote.*.third_party.contentpool_client:
  type: mapping
  label: 'Contentpool client settings'
  mapping:
    autoregister:
      type: integer
      label: 'Marks remote as a contentpool server.'
    autopull:
      type: integer
      label: 'Pull data from this remote automatically.'
    autopull_interval:
      type: string
      label: 'Interval to use for pulling automatically.'
    remote_site_uuid:
      type: string
      label: 'The uuid of the contentpool site.'